S390X_SRC=$(SRC_PATH)/tests/tcg/s390x
VPATH+=$(S390X_SRC)
# EXTFLAGS can be passed by the user, e.g. to override the --accel
QEMU_OPTS+=-action panic=exit-failure -nographic -serial chardev:output $(EXTFLAGS) -kernel
LINK_SCRIPT=$(S390X_SRC)/softmmu.ld
CFLAGS+=-ggdb -O0 -I$(SRC_PATH)/include/hw/s390x/ipl/
LDFLAGS=-nostdlib -static

%.o: %.S
	$(CC) -march=z13 -m64 -Wa,--noexecstack -c $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) -march=z13 -m64 -c $< -o $@

%: %.o
	$(CC) $< -o $@ $(LDFLAGS)

ASM_TESTS =                                                                    \
    art                                                                        \
    asn-control                                                                \
    linkage-exceptions                                                         \
    bal                                                                        \
    bakr                                                                       \
    bassm                                                                      \
    cksm                                                                       \
    clm                                                                        \
    exrl-ssm-early                                                             \
    icm                                                                        \
    ipk                                                                        \
    sam                                                                        \
    lpsw                                                                       \
    lpswe-early                                                                \
    lra                                                                        \
    mc                                                                         \
    pc                                                                         \
    pc-ss                                                                      \
    per                                                                        \
    precise-smc-softmmu                                                        \
    sckc                                                                       \
    ssm-early                                                                  \
    stosm-early                                                                \
    stpq                                                                       \
    unaligned-lowcore

include $(S390X_SRC)/pgm-specification.mak
$(PGM_SPECIFICATION_TESTS): pgm-specification-softmmu.o
$(PGM_SPECIFICATION_TESTS): LDFLAGS+=pgm-specification-softmmu.o
ASM_TESTS += $(PGM_SPECIFICATION_TESTS)

$(ASM_TESTS): LDFLAGS += -Wl,-T$(LINK_SCRIPT) -Wl,--build-id=none
$(ASM_TESTS): $(LINK_SCRIPT)
TESTS += $(ASM_TESTS)

MULTIARCH_TESTS += mvc-smc diag204 decimal edat hfp plo
S390X_MULTIARCH_RUNTIME_OBJS = head64.o console.o $(MINILIB_OBJS)
$(MULTIARCH_TESTS): $(S390X_MULTIARCH_RUNTIME_OBJS)
$(MULTIARCH_TESTS): LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
$(MULTIARCH_TESTS): CFLAGS += $(MINILIB_INC) \
			      -I$(SRC_PATH)/roms/SLOF/lib/libc/include/
diag204: diag204.o
decimal: decimal.o
edat: edat.o
hfp: hfp.o
plo: plo.o
fba-tic: $(S390X_MULTIARCH_RUNTIME_OBJS)
fba-tic: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
TESTS += fba-tic
memory: CFLAGS += -DCHECK_UNALIGNED=0

fba-tic: CFLAGS += -I$(SRC_PATH)/pc-bios/s390-ccw
fba-tic: fba-tic.o
run-fba-tic: QEMU_OPTS := -action panic=exit-failure -nographic \
	-serial chardev:output $(EXTFLAGS) -nodefaults \
	-blockdev driver=null-co$(COMMA)node-name=fba$(COMMA)size=1048576 \
	-device fba-ccw$(COMMA)drive=fba$(COMMA)devno=fe.0.0200 -kernel

# s390x clears the BSS section so we need to account for that
run-plugin-memory-with-libmem.so: 		\
	CHECK_PLUGIN_OUTPUT_COMMAND=$(MULTIARCH_SYSTEM_SRC)/validate-memory-counts.py \
		--bss-cleared $@.out
