S390X_SRC=$(SRC_PATH)/tests/tcg/s390x
VPATH+=$(S390X_SRC)
# EXTFLAGS can be passed by the user, e.g. to override the --accel
QEMU_OPTS+=-action panic=exit-failure -nographic -serial chardev:output $(EXTFLAGS) -kernel
LINK_SCRIPT=$(S390X_SRC)/softmmu.ld
CFLAGS+=-ggdb -O0 -I$(SRC_PATH)/include/hw/s390x/ipl/
LDFLAGS=-nostdlib -static

%.o: %.S
	$(CC) -march=z13 -m64 -Wa,--noexecstack -c $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) -march=z13 -m64 -c $< -o $@

%: %.o
	$(CC) $< -o $@ $(LDFLAGS)

ASM_TESTS =                                                                    \
    art                                                                        \
    asn-control                                                                \
    linkage-exceptions                                                         \
    bal                                                                        \
    bakr                                                                       \
    bassm                                                                      \
    cksm                                                                       \
    dfp-convert                                                                \
    clm                                                                        \
    exrl-ssm-early                                                             \
    icm                                                                        \
    ipk                                                                        \
    keyed-move                                                                 \
    storage-key                                                                \
    sam                                                                        \
    lpsw                                                                       \
    lpswe-early                                                                \
    lra                                                                        \
    mc                                                                         \
    pc                                                                         \
    pc-ss                                                                      \
    pfpo                                                                       \
    pqap                                                                       \
    per                                                                        \
    precise-smc-softmmu                                                        \
    sckc                                                                       \
    ssm-early                                                                  \
    stosm-early                                                                \
    stpq                                                                       \
    strag                                                                      \
    svs                                                                        \
    trace                                                                      \
    trte                                                                       \
    xc-teid                                                                    \
    unaligned-lowcore

include $(S390X_SRC)/pgm-specification.mak
$(PGM_SPECIFICATION_TESTS): pgm-specification-softmmu.o
$(PGM_SPECIFICATION_TESTS): LDFLAGS+=pgm-specification-softmmu.o
ASM_TESTS += $(PGM_SPECIFICATION_TESTS)

$(ASM_TESTS): LDFLAGS += -Wl,-T$(LINK_SCRIPT) -Wl,--build-id=none
$(ASM_TESTS): $(LINK_SCRIPT)
dfp-convert: dfp-convert.o
strag: strag.o
svs: svs.o
xc-teid: xc-teid.o
TESTS += $(ASM_TESTS)

MULTIARCH_TESTS += mvc-smc diag204 decimal edat hfp la plo
S390X_MULTIARCH_RUNTIME_OBJS = head64.o console.o $(MINILIB_OBJS)
$(MULTIARCH_TESTS): $(S390X_MULTIARCH_RUNTIME_OBJS)
$(MULTIARCH_TESTS): LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
$(MULTIARCH_TESTS): CFLAGS += $(MINILIB_INC) \
			      -I$(SRC_PATH)/roms/SLOF/lib/libc/include/
diag204: diag204.o
decimal: decimal.o
edat: edat.o
hfp: hfp.o
la: la.o
plo: plo.o
fba-tic: $(S390X_MULTIARCH_RUNTIME_OBJS)
fba-tic: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
TESTS += fba-tic
memory: CFLAGS += -DCHECK_UNALIGNED=0

fba-tic: CFLAGS += -I$(SRC_PATH)/pc-bios/s390-ccw
fba-tic: fba-tic.o
run-fba-tic: QEMU_OPTS := -action panic=exit-failure -nographic \
	-serial chardev:output $(EXTFLAGS) -nodefaults \
	-blockdev driver=null-co$(COMMA)node-name=fba$(COMMA)size=1048576 \
	-device fba-ccw$(COMMA)drive=fba$(COMMA)devno=fe.0.0200 -kernel

sclp-chp: $(S390X_MULTIARCH_RUNTIME_OBJS)
sclp-chp: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
sclp-chp: CFLAGS += -I$(SRC_PATH)/pc-bios/s390-ccw
sclp-chp: sclp-chp.o
TESTS += sclp-chp
run-sclp-chp: QEMU_OPTS := -action panic=exit-failure -nographic \
	-serial chardev:output $(EXTFLAGS) -nodefaults \
	-blockdev driver=null-co$(COMMA)node-name=fba$(COMMA)size=1048576 \
	-device fba-ccw$(COMMA)drive=fba$(COMMA)devno=fe.0.0200 -kernel

eckd-zero-data: $(S390X_MULTIARCH_RUNTIME_OBJS)
eckd-zero-data: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
eckd-zero-data: CFLAGS += $(MINILIB_INC) -I$(SRC_PATH)/pc-bios/s390-ccw
eckd-zero-data: eckd-zero-data.o
TESTS += eckd-zero-data
run-eckd-zero-data: eckd-zero-data
	$(call run-test, $<, $(PYTHON) $(S390X_SRC)/eckd-zero-data.py \
	  $(QEMU) $<)

tape-write: $(S390X_MULTIARCH_RUNTIME_OBJS)
tape-write: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
tape-write: CFLAGS += $(MINILIB_INC) -I$(SRC_PATH)/pc-bios/s390-ccw
tape-write: tape-write.o
tape-write-protect: $(S390X_MULTIARCH_RUNTIME_OBJS)
tape-write-protect: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
tape-write-protect: CFLAGS += $(MINILIB_INC) -I$(SRC_PATH)/pc-bios/s390-ccw
tape-write-protect: tape-write-protect.o
tape-write-protect.o: tape-write.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) -DTAPE_WRITE_PROTECT_TEST \
	  -march=z13 -m64 -c $< -o $@
TESTS += tape-write tape-write-protect
run-tape-write: tape-write tape-write-protect
	$(call run-test, $<, $(PYTHON) $(S390X_SRC)/tape-write.py \
	  $(QEMU) tape-write tape-write-protect)

terminal3215: $(S390X_MULTIARCH_RUNTIME_OBJS)
terminal3215: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
terminal3215: CFLAGS += $(MINILIB_INC) -I$(SRC_PATH)/pc-bios/s390-ccw
terminal3215: terminal3215.o
TESTS += terminal3215
run-terminal3215: QEMU_OPTS := -action panic=exit-failure -nographic \
	-serial chardev:output $(EXTFLAGS) -nodefaults \
	-chardev ringbuf$(COMMA)id=term$(COMMA)size=4096 \
	-device 3215-ccw$(COMMA)chardev=term$(COMMA)devno=fe.0.0009 -kernel

terminal3215-input: $(S390X_MULTIARCH_RUNTIME_OBJS)
terminal3215-input: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
terminal3215-input: CFLAGS += -I$(SRC_PATH)/pc-bios/s390-ccw
terminal3215-input: terminal3215-input.o
TESTS += terminal3215-input
run-terminal3215-input: terminal3215-input
	$(call run-test, $<, sh -c "{ sleep 1; printf '0 yes\\n'; sleep 1; } | \
	  exec $(QEMU) -monitor none -display none -nodefaults \
	  -action panic=exit-failure -dev3215 devno=009 -kernel $<")

terminal3270-skip: $(S390X_MULTIARCH_RUNTIME_OBJS)
terminal3270-skip: LDFLAGS += $(S390X_MULTIARCH_RUNTIME_OBJS)
terminal3270-skip: CFLAGS += -I$(SRC_PATH)/pc-bios/s390-ccw
terminal3270-skip: terminal3270-skip.o
TESTS += terminal3270-skip
run-terminal3270-skip: terminal3270-skip
	$(call run-test, $<, $(PYTHON) $(S390X_SRC)/terminal3270-skip.py \
	  $(QEMU) $<)

# s390x clears the BSS section so we need to account for that
run-plugin-memory-with-libmem.so: 		\
	CHECK_PLUGIN_OUTPUT_COMMAND=$(MULTIARCH_SYSTEM_SRC)/validate-memory-counts.py \
		--bss-cleared $@.out
